# Generated by Django 6.0.5 on 2026-05-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Alugado', 'Alugado')], default='Disponível', max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], max_length=20),
        ),
    ]
