# Generated by Django 6.0.5 on 2026-05-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.IntegerField()),
                ('cliente', models.CharField(max_length=100)),
                ('dia_inicial', models.DateField()),
                ('dia_final', models.DateField()),
                ('status', models.CharField(choices=[('RESERVADO', 'Reservado'), ('EM_USO', 'Em uso'), ('DEVOLVIDO', 'Devolvido'), ('DEVOLVIDO_ATRASADO', 'Devolvido Atrasado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
