# Generated by Django 6.0.5 on 2026-05-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locacao',
            old_name='veiculo',
            new_name='veiculo_id',
        ),
    ]
